/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;


public class App {

    public String getGreeting() {
        return "Hello, World!";
    }

    public static void main(String[] args) throws IOException {
        String language = args[0];
        InputStream resourcesStream = App.class.getClassLoader().getResourceAsStream(language + ".txt");

        assert resourcesStream != null;
        BufferedReader bufferedInputStream = new BufferedReader(new InputStreamReader(resourcesStream,StandardCharsets.UTF_8));

        System.out.println("Hello, " + bufferedInputStream.readLine() + "!");
    }
}
