/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import java.io.IOException;

public class AppTest {

    @Test
    public void appHasAGreeting() throws IOException {
        App.main(new String[]{"en"});
    }
}

